name: Grabar Audio de Twitch

on:
  workflow_dispatch:
    inputs:
      twitch_channel:
        description: 'Nombre del canal de Twitch a grabar'
        required: true
        type: string

jobs:
  record_and_send:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install streamlink telethon

      - name: Obtener ID del Stream y configurar nombre
        run: |
          set -e
          set -x
          STREAM_ID=$(streamlink --json twitch.tv/${{ inputs.twitch_channel }} 2> streamlink_error.log | jq -r '.metadata.id')
          cat streamlink_error.log
          if [ "$STREAM_ID" == "null" ] || [ -z "$STREAM_ID" ]; then
            echo "STREAM_ID no encontrado, probablemente canal offline o error en streamlink."
            exit 1
          fi
          echo "STREAM_ID es: $STREAM_ID"
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          FILENAME="audio_${{ inputs.twitch_channel }}_${STREAM_ID}_${TIMESTAMP}.m4a"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "FILENAME es: $FILENAME"

      - name: Grabar audio con Streamlink
        run: |
          set -e
          set -x
          echo "Iniciando grabación del canal: ${{ inputs.twitch_channel }}"
          MINUTOS_MAXIMOS=300
          timeout ${MINUTOS_MAXIMOS}m streamlink twitch.tv/${{ inputs.twitch_channel }} audio_only -o "${{ env.FILENAME }}" --twitch-disable-hosting --stream-segment-threads 1 2> streamlink_grab_error.log || [ $? -eq 124 ]
          cat streamlink_grab_error.log
          echo "Grabación finalizada (o tiempo límite alcanzado)."

      - name: Enviar audio a Telegram
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          CANAL_ID: ${{ secrets.CANAL_ID }}
        if: always()
        run: |
          set -e
          set -x
          METADATA=$(streamlink --json twitch.tv/${{ inputs.twitch_channel }} 2> telegram_streamlink_error.log)
          cat telegram_streamlink_error.log
          STREAM_TITLE=$(echo $METADATA | jq -r '.metadata.title')
          STREAM_ID=$(echo $METADATA | jq -r '.metadata.id')
          if [ -z "$STREAM_TITLE" ] || [ "$STREAM_TITLE" == "null" ]; then STREAM_TITLE="Directo sin título"; fi
          if [ -z "$STREAM_ID" ] || [ "$STREAM_ID" == "null" ]; then STREAM_ID="N/A"; fi
          echo "STREAM_TITLE es: $STREAM_TITLE"
          echo "STREAM_ID es: $STREAM_ID"
          python send_telegram.py "${{ env.FILENAME }}" "$STREAM_TITLE" "$STREAM_ID"
